version: '3.8'

services:
  web:
    build: .
    command: pytest
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=your-secret-key
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=shop.settings