name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.ci.yml build

      - name: Run tests
        run: |
          docker-compose -f docker-compose.ci.yml run --rm web pytest

      - name: Run tests
        run: |
          docker-compose run --rm web pytest

      - name: Clean up
        run: |
          docker-compose down